Education resources update
meanjs/meanjs.github.io pull request #31
Opened 2017-07-30 23:43 UTC by miller-productions

doc(0.5.x): Update education resources

Format list of resources as UL, add new item (link to Dan's book Lean MEAN Web App Machine), re-format community section to three columns (consolidate existing) and add new column: Education

2017-08-01 05:12 UTC, miller-productions commented
Hi @lirantal,

This relates to our recent email discussion.

Sincerely,
Dan

2017-08-03 20:24 UTC, lirantal commented on community.html
> +    <h3>Education</h3>
instead of promoting one item over the other, can you simply link from the educational section to `_includes/docs/0.5.x/resources.html` ?

2017-08-03 20:24 UTC, lirantal requested changes

2017-08-03 20:24 UTC, lirantal commented on community.html
> +    <h3>Education</h3>
instead of promoting one item over the other, can you simply link from the educational section to _includes/docs/0.5.x/resources.html ?

2017-08-03 20:25 UTC, lirantal commented
Thanks Dan, appreciate the updates.
We always welcome educational resources to be featured on the page.

2017-08-03 21:10 UTC, miller-productions commented on community.html
> +    <h3>Education</h3>
Understood, yes. 

The new education section could look something more like the following example instead...?

```
<div class="col-md-4">
    <h3>Education</h3>
    <p>
      View the current list of <a href="http://meanjs.org/docs/0.5.x/#resources">educational resources</a> available to support your MEAN.JS development.
    </p>
  </div>
```
What do you think?

Example screenshot below...

![image](https://user-images.githubusercontent.com/15177547/28943881-b86d781c-78e3-11e7-83e8-25f9fe52ee36.png)

2017-08-04 07:05 UTC, lirantal commented on community.html
> +    <h3>Education</h3>
yep, looks good.

2017-08-04 07:58 UTC, miller-productions commented
Thanks Liran,

Changes completed.

2017-08-04 15:50 UTC, merged